[Settings]
doc_log = yes
file_log = yes

[Key]
; groq_key = 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
SERPAPI_API_KEY = 17d0cd1af3add9e3bddd6c5f78ebb6b1d0dc43ca3128c88852586fa70f2a3dfc
groq_key = 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 # Jenith
; groq_key = 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 # Jenith
; groq_key = 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 # Jenith
; groq_key = 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 # vishal_chauhan  